---
apiVersion: v1
kind: Service
metadata:
  name: "myblog"
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: myblog-service_mapping
      host: myblog.stage.sunlighten.io
      prefix: /
      service: myblog:8080
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 80
  selector:
    app: myblog
